/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.dokstrudio.med.srv.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ApplicationAccount service. Represents a row in the &quot;med_ApplicationAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.dokstrudio.med.srv.model.impl.ApplicationAccountModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.dokstrudio.med.srv.model.impl.ApplicationAccountImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApplicationAccount
 * @see ru.dokstrudio.med.srv.model.impl.ApplicationAccountImpl
 * @see ru.dokstrudio.med.srv.model.impl.ApplicationAccountModelImpl
 * @generated
 */
@ProviderType
public interface ApplicationAccountModel extends BaseModel<ApplicationAccount> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application account model instance should use the {@link ApplicationAccount} interface instead.
	 */

	/**
	 * Returns the primary key of this application account.
	 *
	 * @return the primary key of this application account
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this application account.
	 *
	 * @param primaryKey the primary key of this application account
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the account type ID of this application account.
	 *
	 * @return the account type ID of this application account
	 */
	public long getAccountTypeId();

	/**
	 * Sets the account type ID of this application account.
	 *
	 * @param accountTypeId the account type ID of this application account
	 */
	public void setAccountTypeId(long accountTypeId);

	/**
	 * Returns the name of this application account.
	 *
	 * @return the name of this application account
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this application account.
	 *
	 * @param name the name of this application account
	 */
	public void setName(String name);

	/**
	 * Returns the description of this application account.
	 *
	 * @return the description of this application account
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this application account.
	 *
	 * @param description the description of this application account
	 */
	public void setDescription(String description);

	/**
	 * Returns the duration days of this application account.
	 *
	 * @return the duration days of this application account
	 */
	public long getDurationDays();

	/**
	 * Sets the duration days of this application account.
	 *
	 * @param durationDays the duration days of this application account
	 */
	public void setDurationDays(long durationDays);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ru.dokstrudio.med.srv.model.ApplicationAccount applicationAccount);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ru.dokstrudio.med.srv.model.ApplicationAccount> toCacheModel();

	@Override
	public ru.dokstrudio.med.srv.model.ApplicationAccount toEscapedModel();

	@Override
	public ru.dokstrudio.med.srv.model.ApplicationAccount toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}