/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.dokstrudio.med.srv.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TestUnitAttempt service. Represents a row in the &quot;med_TestUnitAttempt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.dokstrudio.med.srv.model.impl.TestUnitAttemptModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.dokstrudio.med.srv.model.impl.TestUnitAttemptImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TestUnitAttempt
 * @see ru.dokstrudio.med.srv.model.impl.TestUnitAttemptImpl
 * @see ru.dokstrudio.med.srv.model.impl.TestUnitAttemptModelImpl
 * @generated
 */
@ProviderType
public interface TestUnitAttemptModel extends BaseModel<TestUnitAttempt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test unit attempt model instance should use the {@link TestUnitAttempt} interface instead.
	 */

	/**
	 * Returns the primary key of this test unit attempt.
	 *
	 * @return the primary key of this test unit attempt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test unit attempt.
	 *
	 * @param primaryKey the primary key of this test unit attempt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the test unit attempt ID of this test unit attempt.
	 *
	 * @return the test unit attempt ID of this test unit attempt
	 */
	public long getTestUnitAttemptId();

	/**
	 * Sets the test unit attempt ID of this test unit attempt.
	 *
	 * @param testUnitAttemptId the test unit attempt ID of this test unit attempt
	 */
	public void setTestUnitAttemptId(long testUnitAttemptId);

	/**
	 * Returns the user ID of this test unit attempt.
	 *
	 * @return the user ID of this test unit attempt
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this test unit attempt.
	 *
	 * @param userId the user ID of this test unit attempt
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this test unit attempt.
	 *
	 * @return the user uuid of this test unit attempt
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this test unit attempt.
	 *
	 * @param userUuid the user uuid of this test unit attempt
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the test unit ID of this test unit attempt.
	 *
	 * @return the test unit ID of this test unit attempt
	 */
	public long getTestUnitId();

	/**
	 * Sets the test unit ID of this test unit attempt.
	 *
	 * @param testUnitId the test unit ID of this test unit attempt
	 */
	public void setTestUnitId(long testUnitId);

	/**
	 * Returns the test unit answer ID of this test unit attempt.
	 *
	 * @return the test unit answer ID of this test unit attempt
	 */
	public long getTestUnitAnswerId();

	/**
	 * Sets the test unit answer ID of this test unit attempt.
	 *
	 * @param testUnitAnswerId the test unit answer ID of this test unit attempt
	 */
	public void setTestUnitAnswerId(long testUnitAnswerId);

	/**
	 * Returns the submit time of this test unit attempt.
	 *
	 * @return the submit time of this test unit attempt
	 */
	public Date getSubmitTime();

	/**
	 * Sets the submit time of this test unit attempt.
	 *
	 * @param submitTime the submit time of this test unit attempt
	 */
	public void setSubmitTime(Date submitTime);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ru.dokstrudio.med.srv.model.TestUnitAttempt testUnitAttempt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ru.dokstrudio.med.srv.model.TestUnitAttempt> toCacheModel();

	@Override
	public ru.dokstrudio.med.srv.model.TestUnitAttempt toEscapedModel();

	@Override
	public ru.dokstrudio.med.srv.model.TestUnitAttempt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}