/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.dokstrudio.med.srv.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import ru.dokstrudio.med.srv.service.persistence.UserAccountPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserAccount service. Represents a row in the &quot;med_UserAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.dokstrudio.med.srv.model.impl.UserAccountModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.dokstrudio.med.srv.model.impl.UserAccountImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserAccount
 * @see ru.dokstrudio.med.srv.model.impl.UserAccountImpl
 * @see ru.dokstrudio.med.srv.model.impl.UserAccountModelImpl
 * @generated
 */
@ProviderType
public interface UserAccountModel extends BaseModel<UserAccount> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user account model instance should use the {@link UserAccount} interface instead.
	 */

	/**
	 * Returns the primary key of this user account.
	 *
	 * @return the primary key of this user account
	 */
	public UserAccountPK getPrimaryKey();

	/**
	 * Sets the primary key of this user account.
	 *
	 * @param primaryKey the primary key of this user account
	 */
	public void setPrimaryKey(UserAccountPK primaryKey);

	/**
	 * Returns the user ID of this user account.
	 *
	 * @return the user ID of this user account
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user account.
	 *
	 * @param userId the user ID of this user account
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user account.
	 *
	 * @return the user uuid of this user account
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user account.
	 *
	 * @param userUuid the user uuid of this user account
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the account type ID of this user account.
	 *
	 * @return the account type ID of this user account
	 */
	public long getAccountTypeId();

	/**
	 * Sets the account type ID of this user account.
	 *
	 * @param accountTypeId the account type ID of this user account
	 */
	public void setAccountTypeId(long accountTypeId);

	/**
	 * Returns the activation date of this user account.
	 *
	 * @return the activation date of this user account
	 */
	public Date getActivationDate();

	/**
	 * Sets the activation date of this user account.
	 *
	 * @param activationDate the activation date of this user account
	 */
	public void setActivationDate(Date activationDate);

	/**
	 * Returns the expiration date of this user account.
	 *
	 * @return the expiration date of this user account
	 */
	public Date getExpirationDate();

	/**
	 * Sets the expiration date of this user account.
	 *
	 * @param expirationDate the expiration date of this user account
	 */
	public void setExpirationDate(Date expirationDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ru.dokstrudio.med.srv.model.UserAccount userAccount);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ru.dokstrudio.med.srv.model.UserAccount> toCacheModel();

	@Override
	public ru.dokstrudio.med.srv.model.UserAccount toEscapedModel();

	@Override
	public ru.dokstrudio.med.srv.model.UserAccount toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}