/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.dokstrudio.med.srv.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the UserDevice service. Represents a row in the &quot;med_UserDevice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.dokstrudio.med.srv.model.impl.UserDeviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.dokstrudio.med.srv.model.impl.UserDeviceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserDevice
 * @see ru.dokstrudio.med.srv.model.impl.UserDeviceImpl
 * @see ru.dokstrudio.med.srv.model.impl.UserDeviceModelImpl
 * @generated
 */
@ProviderType
public interface UserDeviceModel extends BaseModel<UserDevice> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user device model instance should use the {@link UserDevice} interface instead.
	 */

	/**
	 * Returns the primary key of this user device.
	 *
	 * @return the primary key of this user device
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user device.
	 *
	 * @param primaryKey the primary key of this user device
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the device ID of this user device.
	 *
	 * @return the device ID of this user device
	 */
	public long getDeviceId();

	/**
	 * Sets the device ID of this user device.
	 *
	 * @param deviceId the device ID of this user device
	 */
	public void setDeviceId(long deviceId);

	/**
	 * Returns the user ID of this user device.
	 *
	 * @return the user ID of this user device
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user device.
	 *
	 * @param userId the user ID of this user device
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user device.
	 *
	 * @return the user uuid of this user device
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user device.
	 *
	 * @param userUuid the user uuid of this user device
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the device type ID of this user device.
	 *
	 * @return the device type ID of this user device
	 */
	public int getDeviceTypeId();

	/**
	 * Sets the device type ID of this user device.
	 *
	 * @param deviceTypeId the device type ID of this user device
	 */
	public void setDeviceTypeId(int deviceTypeId);

	/**
	 * Returns the device key of this user device.
	 *
	 * @return the device key of this user device
	 */
	@AutoEscape
	public String getDeviceKey();

	/**
	 * Sets the device key of this user device.
	 *
	 * @param deviceKey the device key of this user device
	 */
	public void setDeviceKey(String deviceKey);

	/**
	 * Returns the operating system of this user device.
	 *
	 * @return the operating system of this user device
	 */
	@AutoEscape
	public String getOperatingSystem();

	/**
	 * Sets the operating system of this user device.
	 *
	 * @param operatingSystem the operating system of this user device
	 */
	public void setOperatingSystem(String operatingSystem);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ru.dokstrudio.med.srv.model.UserDevice userDevice);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ru.dokstrudio.med.srv.model.UserDevice> toCacheModel();

	@Override
	public ru.dokstrudio.med.srv.model.UserDevice toEscapedModel();

	@Override
	public ru.dokstrudio.med.srv.model.UserDevice toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}