/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.dokstudio.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import ru.dokstudio.model.TestItemAttempt;

import ru.dokstudio.service.TestItemAttemptService;
import ru.dokstudio.service.persistence.TestItemAnswerPersistence;
import ru.dokstudio.service.persistence.TestItemAttemptPersistence;
import ru.dokstudio.service.persistence.TestItemQuestionPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the test item attempt remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link ru.dokstudio.service.impl.TestItemAttemptServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ru.dokstudio.service.impl.TestItemAttemptServiceImpl
 * @see ru.dokstudio.service.TestItemAttemptServiceUtil
 * @generated
 */
public abstract class TestItemAttemptServiceBaseImpl extends BaseServiceImpl
	implements TestItemAttemptService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link ru.dokstudio.service.TestItemAttemptServiceUtil} to access the test item attempt remote service.
	 */

	/**
	 * Returns the test item answer local service.
	 *
	 * @return the test item answer local service
	 */
	public ru.dokstudio.service.TestItemAnswerLocalService getTestItemAnswerLocalService() {
		return testItemAnswerLocalService;
	}

	/**
	 * Sets the test item answer local service.
	 *
	 * @param testItemAnswerLocalService the test item answer local service
	 */
	public void setTestItemAnswerLocalService(
		ru.dokstudio.service.TestItemAnswerLocalService testItemAnswerLocalService) {
		this.testItemAnswerLocalService = testItemAnswerLocalService;
	}

	/**
	 * Returns the test item answer remote service.
	 *
	 * @return the test item answer remote service
	 */
	public ru.dokstudio.service.TestItemAnswerService getTestItemAnswerService() {
		return testItemAnswerService;
	}

	/**
	 * Sets the test item answer remote service.
	 *
	 * @param testItemAnswerService the test item answer remote service
	 */
	public void setTestItemAnswerService(
		ru.dokstudio.service.TestItemAnswerService testItemAnswerService) {
		this.testItemAnswerService = testItemAnswerService;
	}

	/**
	 * Returns the test item answer persistence.
	 *
	 * @return the test item answer persistence
	 */
	public TestItemAnswerPersistence getTestItemAnswerPersistence() {
		return testItemAnswerPersistence;
	}

	/**
	 * Sets the test item answer persistence.
	 *
	 * @param testItemAnswerPersistence the test item answer persistence
	 */
	public void setTestItemAnswerPersistence(
		TestItemAnswerPersistence testItemAnswerPersistence) {
		this.testItemAnswerPersistence = testItemAnswerPersistence;
	}

	/**
	 * Returns the test item attempt local service.
	 *
	 * @return the test item attempt local service
	 */
	public ru.dokstudio.service.TestItemAttemptLocalService getTestItemAttemptLocalService() {
		return testItemAttemptLocalService;
	}

	/**
	 * Sets the test item attempt local service.
	 *
	 * @param testItemAttemptLocalService the test item attempt local service
	 */
	public void setTestItemAttemptLocalService(
		ru.dokstudio.service.TestItemAttemptLocalService testItemAttemptLocalService) {
		this.testItemAttemptLocalService = testItemAttemptLocalService;
	}

	/**
	 * Returns the test item attempt remote service.
	 *
	 * @return the test item attempt remote service
	 */
	public TestItemAttemptService getTestItemAttemptService() {
		return testItemAttemptService;
	}

	/**
	 * Sets the test item attempt remote service.
	 *
	 * @param testItemAttemptService the test item attempt remote service
	 */
	public void setTestItemAttemptService(
		TestItemAttemptService testItemAttemptService) {
		this.testItemAttemptService = testItemAttemptService;
	}

	/**
	 * Returns the test item attempt persistence.
	 *
	 * @return the test item attempt persistence
	 */
	public TestItemAttemptPersistence getTestItemAttemptPersistence() {
		return testItemAttemptPersistence;
	}

	/**
	 * Sets the test item attempt persistence.
	 *
	 * @param testItemAttemptPersistence the test item attempt persistence
	 */
	public void setTestItemAttemptPersistence(
		TestItemAttemptPersistence testItemAttemptPersistence) {
		this.testItemAttemptPersistence = testItemAttemptPersistence;
	}

	/**
	 * Returns the test item question local service.
	 *
	 * @return the test item question local service
	 */
	public ru.dokstudio.service.TestItemQuestionLocalService getTestItemQuestionLocalService() {
		return testItemQuestionLocalService;
	}

	/**
	 * Sets the test item question local service.
	 *
	 * @param testItemQuestionLocalService the test item question local service
	 */
	public void setTestItemQuestionLocalService(
		ru.dokstudio.service.TestItemQuestionLocalService testItemQuestionLocalService) {
		this.testItemQuestionLocalService = testItemQuestionLocalService;
	}

	/**
	 * Returns the test item question remote service.
	 *
	 * @return the test item question remote service
	 */
	public ru.dokstudio.service.TestItemQuestionService getTestItemQuestionService() {
		return testItemQuestionService;
	}

	/**
	 * Sets the test item question remote service.
	 *
	 * @param testItemQuestionService the test item question remote service
	 */
	public void setTestItemQuestionService(
		ru.dokstudio.service.TestItemQuestionService testItemQuestionService) {
		this.testItemQuestionService = testItemQuestionService;
	}

	/**
	 * Returns the test item question persistence.
	 *
	 * @return the test item question persistence
	 */
	public TestItemQuestionPersistence getTestItemQuestionPersistence() {
		return testItemQuestionPersistence;
	}

	/**
	 * Sets the test item question persistence.
	 *
	 * @param testItemQuestionPersistence the test item question persistence
	 */
	public void setTestItemQuestionPersistence(
		TestItemQuestionPersistence testItemQuestionPersistence) {
		this.testItemQuestionPersistence = testItemQuestionPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return TestItemAttemptService.class.getName();
	}

	protected Class<?> getModelClass() {
		return TestItemAttempt.class;
	}

	protected String getModelClassName() {
		return TestItemAttempt.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = testItemAttemptPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ru.dokstudio.service.TestItemAnswerLocalService.class)
	protected ru.dokstudio.service.TestItemAnswerLocalService testItemAnswerLocalService;
	@BeanReference(type = ru.dokstudio.service.TestItemAnswerService.class)
	protected ru.dokstudio.service.TestItemAnswerService testItemAnswerService;
	@BeanReference(type = TestItemAnswerPersistence.class)
	protected TestItemAnswerPersistence testItemAnswerPersistence;
	@BeanReference(type = ru.dokstudio.service.TestItemAttemptLocalService.class)
	protected ru.dokstudio.service.TestItemAttemptLocalService testItemAttemptLocalService;
	@BeanReference(type = TestItemAttemptService.class)
	protected TestItemAttemptService testItemAttemptService;
	@BeanReference(type = TestItemAttemptPersistence.class)
	protected TestItemAttemptPersistence testItemAttemptPersistence;
	@BeanReference(type = ru.dokstudio.service.TestItemQuestionLocalService.class)
	protected ru.dokstudio.service.TestItemQuestionLocalService testItemQuestionLocalService;
	@BeanReference(type = ru.dokstudio.service.TestItemQuestionService.class)
	protected ru.dokstudio.service.TestItemQuestionService testItemQuestionService;
	@BeanReference(type = TestItemQuestionPersistence.class)
	protected TestItemQuestionPersistence testItemQuestionPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}