/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.dokstudio.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TestItemAttempt service. Represents a row in the &quot;gmt_TestItemAttempt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.dokstudio.model.impl.TestItemAttemptModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.dokstudio.model.impl.TestItemAttemptImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TestItemAttempt
 * @see ru.dokstudio.model.impl.TestItemAttemptImpl
 * @see ru.dokstudio.model.impl.TestItemAttemptModelImpl
 * @generated
 */
@ProviderType
public interface TestItemAttemptModel extends BaseModel<TestItemAttempt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test item attempt model instance should use the {@link TestItemAttempt} interface instead.
	 */

	/**
	 * Returns the primary key of this test item attempt.
	 *
	 * @return the primary key of this test item attempt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test item attempt.
	 *
	 * @param primaryKey the primary key of this test item attempt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this test item attempt.
	 *
	 * @return the uuid of this test item attempt
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this test item attempt.
	 *
	 * @param uuid the uuid of this test item attempt
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the attempt ID of this test item attempt.
	 *
	 * @return the attempt ID of this test item attempt
	 */
	public long getAttemptId();

	/**
	 * Sets the attempt ID of this test item attempt.
	 *
	 * @param attemptId the attempt ID of this test item attempt
	 */
	public void setAttemptId(long attemptId);

	/**
	 * Returns the question ID of this test item attempt.
	 *
	 * @return the question ID of this test item attempt
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this test item attempt.
	 *
	 * @param questionId the question ID of this test item attempt
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the answer ID of this test item attempt.
	 *
	 * @return the answer ID of this test item attempt
	 */
	public long getAnswerId();

	/**
	 * Sets the answer ID of this test item attempt.
	 *
	 * @param answerId the answer ID of this test item attempt
	 */
	public void setAnswerId(long answerId);

	/**
	 * Returns the is success attempt of this test item attempt.
	 *
	 * @return the is success attempt of this test item attempt
	 */
	public boolean getIsSuccessAttempt();

	/**
	 * Returns <code>true</code> if this test item attempt is is success attempt.
	 *
	 * @return <code>true</code> if this test item attempt is is success attempt; <code>false</code> otherwise
	 */
	public boolean isIsSuccessAttempt();

	/**
	 * Sets whether this test item attempt is is success attempt.
	 *
	 * @param isSuccessAttempt the is success attempt of this test item attempt
	 */
	public void setIsSuccessAttempt(boolean isSuccessAttempt);

	/**
	 * Returns the attempt date of this test item attempt.
	 *
	 * @return the attempt date of this test item attempt
	 */
	public Date getAttemptDate();

	/**
	 * Sets the attempt date of this test item attempt.
	 *
	 * @param attemptDate the attempt date of this test item attempt
	 */
	public void setAttemptDate(Date attemptDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ru.dokstudio.model.TestItemAttempt testItemAttempt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ru.dokstudio.model.TestItemAttempt> toCacheModel();

	@Override
	public ru.dokstudio.model.TestItemAttempt toEscapedModel();

	@Override
	public ru.dokstudio.model.TestItemAttempt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}